#!/bin/bash
read r
for((i=0;i<=$r;i++))
do
sum=0
temp=$i
while(($temp>0))
do
rem=`expr $temp % 10`
temp=`expr $temp / 10`
sum=`expr $sum \* 10 + $rem `
done
if(($sum == $i))
then
echo -n "$i "
fi
done
