#!/bin/bash
echo "enter no1"
read no1
echo "enter no2"
read no2
echo "enter operation"
echo "1. add"
echo "2.sub"
echo "3. multi"
echo "4.div"
read op
case $op in
"1")
res=`echo $no1+$no2|bc`
;;
"2")
res=`echo $no1-$no2|bc` 
;;
"3")
res=`echo $no1\*$no2|bc`
;;
"4")
res=`echo $no1/$no2|bc`
;;  
esac
echo $res
